Repository pauldouane/arvz, pull requests merged in 2024-03, with the labels that each got.

#1 feat(): Clean base for project
  .gitignore
  .rustfmt.toml
  Cargo.lock
  Cargo.toml
  Justfile
  build.rs
  rust-toolchain.toml
  src/action.rs
  src/app.rs
  src/cli.rs
  src/components.rs
  src/components/ascii.rs
  src/components/command_search.rs
  src/components/context_informations.rs
  src/components/fps.rs
  src/components/shortcut.rs
  src/components/status_bar.rs
  src/components/table_dag_runs.rs
  src/config.rs
  src/main.rs
  src/mode.rs
  src/models/conf.rs
  src/models/dag_run.rs
  src/models/dag_runs.rs
  src/models/log.rs
  src/models/mod.rs
  src/models/task.rs
  src/models/tasks.rs
  src/style/mod.rs
  src/style/row.rs
  src/tui.rs
  src/utils.rs
Labels: enhancement

#3 chore(gitignore): Remove .fleet in gitignore
  .gitignore
Labels: gitignore

#4 feat: Create table view for source code of dag
  src/action.rs
  src/app.rs
  src/components/table_dag_runs.rs
  src/mode.rs
  src/models/dag.rs
  src/models/dag_run.rs
  src/models/mod.rs
  src/utils.rs
Labels: feature

#5 fix(model): Change next_dag_run i32 -> String
  src/models/dag.rs
Labels: bug

#6 feat(code/logs): Add scrolling feature
  src/action.rs
  src/app.rs
  src/components/table_dag_runs.rs
Labels: feature

#7 fix: Remove default config for clippy error
  src/components/table_dag_runs.rs
  src/config.rs
Labels: bug

#9 feat: Add command component and ui
  src/action.rs
  src/app.rs
  src/components.rs
  src/components/command.rs
  src/mode.rs
Labels: feature

#8 chore(ui): Add margin to the main chunk
  src/app.rs
Labels: chore

#14 refacto(ui): Change system of generation main ui
  src/app.rs
  src/main.rs
  src/main_layout.rs
  src/mode.rs
  src/tui.rs
Labels: refactor, ui
